# Generated by Django 2.1.5 on 2019-02-11 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('adhaarId', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('address', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(max_length=70)),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField()),
                ('disease', models.TextField()),
                ('treatment', models.TextField()),
                ('treated_by', models.CharField(max_length=50)),
                ('payment', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='webapp.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
