# Generated by Django 2.1.5 on 2019-02-06 06:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hosital_name', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(max_length=70)),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField()),
                ('disease', models.TextField()),
                ('treatment', models.TextField()),
                ('treated_by', models.CharField(max_length=50)),
                ('payment', models.IntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='webapp.Patient')),
            ],
        ),
    ]
