# Generated by Django 2.1.5 on 2019-02-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='hosital_name',
            new_name='hospital_name',
        ),
    ]
