# Generated by Django 2.1.5 on 2019-02-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190211_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='adhaarId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
